//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assi
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentss
    {
       
        public int ID { get; set; }
        public string SName { get; set; }
        public string Spassword { get; set; }
        public string SEmail { get; set; }
        public string SAddress { get; set; }
        public Nullable<int> SAge { get; set; }
        public Nullable<int> Depld { get; set; }
    
        public virtual department department { get; set; }
    }
}
